//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_EmployeeMaster
    {
        public int Row_Id { get; set; }
        public string EmployeeCode { get; set; }

        [Required(ErrorMessage ="First Name is Required.")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "last Name is Required.")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Cuntry Name is Required.")]
        public Nullable<long> CountryId { get; set; }

        [Required(ErrorMessage = "State Name is Required.")]
        public Nullable<long> StateId { get; set; }
        [Required(ErrorMessage = "City Name is Required.")]
        public Nullable<long> CityId { get; set; }
        [Required(ErrorMessage = "Email Id is Required.")]
        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "Mobile Number is Required.")]
        public string MobileNumber { get; set; }
        [Required(ErrorMessage = "Pan Number is Required.")]
        public string PanNumber { get; set; }
        [Required(ErrorMessage = "Passport Number is Required.")]
        public string PassportNumber { get; set; }

        public string ProfileImage { get; set; }
        [Required(ErrorMessage = "Gender Fiels is Required.")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "IsActive Field is Required.")]
        public bool IsActive { get; set; }
        //[Required(ErrorMessage = "Date of birth is required.")]
        //[DataType(DataType.Date)]
        [Required(ErrorMessage = "Date of Birth is Required.")]
        public System.DateTime DateOfBirth { get; set; }
        [Required(ErrorMessage = "Date Of join is Required.")]
        public Nullable<System.DateTime> DateOfJoinee { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }

    public partial class EmployeeMaster
    {
        public int Row_Id { get; set; }
        public string EmployeeCode { get; set; }

        [Required(ErrorMessage = "First Name is Required.")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "last Name is Required.")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Cuntry Name is Required.")]
        public string CountryName { get; set; }

        [Required(ErrorMessage = "State Name is Required.")]
        public string StateName { get; set; }
        [Required(ErrorMessage = "City Name is Required.")]
        public string CityName { get; set; }
        [Required(ErrorMessage = "Email Id is Required.")]
        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "Mobile Number is Required.")]
        public string MobileNumber { get; set; }
        [Required(ErrorMessage = "Pan Number is Required.")]
        public string PanNumber { get; set; }
        [Required(ErrorMessage = "Passport Number is Required.")]
        public string PassportNumber { get; set; }

        public string ProfileImage { get; set; }
        [Required(ErrorMessage = "Gender Fiels is Required.")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "IsActive Field is Required.")]
        public Int32 IsActive { get; set; }
        //[Required(ErrorMessage = "Date of birth is required.")]
        //[DataType(DataType.Date)]
        [Required(ErrorMessage = "Date of Birth is Required.")]
        public System.DateTime DateOfBirth { get; set; }
        [Required(ErrorMessage = "Date Of join is Required.")]
        public Nullable<System.DateTime> DateOfJoinee { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }



}
